name: Deploy

on:
  push:
    branches:
      - master
  schedule:
    # cron every week on monday
    - cron: "0 0 * * 1"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Build and Deploy Image
        run: bash scripts/build-push.sh
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
