name: Test

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    strategy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Image
        run: bash scripts/build.sh
